"""Games Team relations

Revision ID: a55e77b6ae05
Revises: 884c818f1cd3
Create Date: 2023-10-18 16:03:00.785864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a55e77b6ae05'
down_revision = '884c818f1cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team1_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('team2_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('games_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('games_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team1_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['team2_id'], ['id'])
        batch_op.drop_column('team1')
        batch_op.drop_column('team2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team2', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('team1', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('games_ibfk_2', 'teams', ['team2'], ['id'])
        batch_op.create_foreign_key('games_ibfk_1', 'teams', ['team1'], ['id'])
        batch_op.drop_column('team2_id')
        batch_op.drop_column('team1_id')

    # ### end Alembic commands ###
