"""Added game and correct picks to Picks db

Revision ID: f96cc24b00fb
Revises: 1617e55def4f
Create Date: 2023-10-20 16:43:52.851026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96cc24b00fb'
down_revision = '1617e55def4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('correctPicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_column('correctPicks')
        batch_op.drop_column('game')

    # ### end Alembic commands ###
